# Лабораторна робота №1

Романенко Ілля ФІТ 4-7

23 варіант

In [263]:
import numpy as np

## Завдання 1

Створіть одновимірний масив (вектор) зі значеннями квадратних коренів з кожного
натурального числа, починаючи з 1, та виведіть його значення.

In [264]:
n = 10
natural_numbers = np.arange(1, n+1)

sqrt_array = np.round(np.sqrt(natural_numbers), 2)

print(sqrt_array)

[1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.   3.16]


## Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
коренів 4 ступеня перших дійсних чисел.

In [265]:

matrix = np.round(np.power(np.arange(1, 10).reshape(3, 3), 1/4), 2)

print(matrix)


[[1.   1.19 1.32]
 [1.41 1.5  1.57]
 [1.63 1.68 1.73]]


## Завдання 3

Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 50 та знайдіть суму елементів кожного рядка.

In [266]:
matrix_3 = np.random.randint(1, 51, size=(3, 3))

print(matrix_3)
print(np.sum(matrix_3, axis=1))

[[13 38 21]
 [22 21 17]
 [39 23 39]]
[ 72  60 101]


## Завдання 4

Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9
до 0.9 та виведіть його значення.

In [267]:
matrix_4 = np.random.randint(-90, 90, size=(4, 4))
matrix_4 = matrix_4 / 100

print(matrix_4)

[[-0.72 -0.64 -0.51 -0.51]
 [ 0.78 -0.34 -0.79 -0.14]
 [ 0.89 -0.21 -0.12  0.28]
 [-0.67 -0.09  0.19  0.8 ]]


In [268]:
# або
matrix_4_alt = np.round(np.random.uniform(-0.9, 0.9, size=(4, 4)), 2)

print(matrix_4_alt)

[[ 0.47  0.33  0.16 -0.04]
 [-0.05 -0.85 -0.18  0.67]
 [-0.89  0.41 -0.5   0.75]
 [ 0.2  -0.43  0.32  0.16]]


## Завдання 5

Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [269]:
arr5_1 = np.random.randint(1, 6, size=7)
arr5_2 = np.random.randint(1, 6, size=7)

print('початкові кортежі')
print(arr5_1)
print(arr5_2)

print('додавання ', arr5_1 + arr5_2)
print('віднімання ', arr5_1 - arr5_2)
print('множення ', arr5_1 * arr5_2)

початкові кортежі
[3 1 2 5 5 1 3]
[1 2 2 1 4 3 3]
додавання  [4 3 4 6 9 4 6]
віднімання  [ 2 -1  0  4  1 -2  0]
множення  [ 3  2  4  5 20  3  9]


## Завдання 6

Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 0 до 5 та
знайдіть їх добуток

In [270]:
matrix6_1 = np.random.randint(0, 6, size=(3, 3))
matrix6_2 = np.random.randint(0, 6, size=(3, 3))

print('початкові матриці')
print(matrix6_1)
print(matrix6_2)

print('\nдобуток матриць\n', np.dot(matrix6_1, matrix6_2))

початкові матриці
[[1 2 4]
 [1 1 2]
 [2 2 5]]
[[2 5 5]
 [5 0 1]
 [3 4 4]]

добуток матриць
 [[24 21 23]
 [13 13 14]
 [29 30 32]]


## Завдання 7

Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [271]:
matrix7_1 = np.random.randint(1, 8, size=(2, 3))
matrix7_2 = np.random.randint(1, 8, size=(3, 4))

print('початкові матриці')
print(matrix7_1)
print(matrix7_2)

print('\nготова матриця\n', np.dot(matrix7_1, matrix7_2))

початкові матриці
[[3 1 6]
 [1 6 7]]
[[6 4 1 5]
 [7 5 1 3]
 [1 4 3 1]]

готова матриця
 [[31 41 22 24]
 [55 62 28 30]]


## Завдання 8

Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 15 та знайдіть її обернену матрицю.

In [272]:
matrix8 = np.random.randint(1, 16, size=(2, 2))

print('оригінальна матриця\n', matrix8)
print('обернена матриця\n', np.linalg.inv(matrix8))

оригінальна матриця
 [[ 2 12]
 [12  4]]
обернена матриця
 [[-0.02941176  0.08823529]
 [ 0.08823529 -0.01470588]]


## Завдання 9

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 3 до 15 та транспонуйте її.

In [273]:
matrix9 = np.random.randint(3, 16, size=(3, 3))

print('оригінальна матриця\n', matrix9)
print('транспонована матриця\n', np.transpose(matrix9))

оригінальна матриця
 [[11  8  3]
 [ 9  3 12]
 [13 14  7]]
транспонована матриця
 [[11  9 13]
 [ 8  3 14]
 [ 3 12  7]]


## Завдання 10

Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [274]:
matrix10 = np.random.randint(1, 11, size=(3, 4))
vector10 = np.random.randint(1, 11, size=(4, 1))

print('матриця\n', matrix10)
print('вектор\n', vector10)
print('результат\n', np.dot(matrix10, vector10))

матриця
 [[ 9  2  8 10]
 [ 1  4  2  5]
 [ 4  8  1  4]]
вектор
 [[3]
 [9]
 [5]
 [5]]
результат
 [[135]
 [ 74]
 [109]]


## Завдання 11

Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [275]:
matrix11 = np.round(np.random.uniform(0, 2, size=(2, 3)), 2)
vector11 = np.round(np.random.uniform(0, 2, size=(3, 1)), 2)

print('матриця\n', matrix11)
print('вектор\n', vector11)

print('результат\n', np.dot(matrix11, vector11))

матриця
 [[1.61 1.17 1.1 ]
 [0.06 0.4  0.87]]
вектор
 [[0.57]
 [1.43]
 [0.39]]
результат
 [[3.0198]
 [0.9455]]


## Завддання 12

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть добуток всіх елементів першої матриці.

In [276]:
matrix12_1 = np.random.randint(1, 6, size=(3, 3))
matrix12_2 = np.random.randint(1, 6, size=(3, 3))

print(matrix12_1)
print(matrix12_2)

print('добуток всіх елементів першої матриці', np.prod(matrix12_1))

[[1 1 1]
 [3 4 5]
 [3 4 2]]
[[3 3 2]
 [4 3 2]
 [4 3 4]]
добуток всіх елементів першої матриці 1440


## Завдання 13

Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть різницю їх елементів.

In [277]:
matrix13_1 = np.round(np.random.uniform(-1, 1, size=(3, 3)), 2)
matrix13_2 = np.round(np.random.uniform(-1, 1, size=(3, 3)), 2)

print('матриця1\n', matrix13_1)
print('матриця2\n', matrix13_2)

print('їх різниця елементів\n', matrix13_1 - matrix13_2)

матриця1
 [[-0.53 -0.1  -0.87]
 [-0.1   0.38 -0.59]
 [ 0.96  0.4   0.29]]
матриця2
 [[-0.34  0.89  0.08]
 [ 0.48  0.52 -0.98]
 [-0.58  0.01 -0.32]]
їх різниця елементів
 [[-0.19 -0.99 -0.95]
 [-0.58 -0.14  0.39]
 [ 1.54  0.39  0.61]]


## Завдання 14

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -3 до 3 та знайдіть суму елементів на головній діагоналі.

In [278]:
matrix14 = np.round(np.random.uniform(-3, 3, size=(3, 3)), 2)

print('матриця\n', matrix14)
print('сума на головній діагоналі ', np.trace(matrix14))

матриця
 [[-2.2  -1.39 -1.12]
 [-2.55  0.57  1.81]
 [-1.83 -1.74 -2.29]]
сума на головній діагоналі  -3.9200000000000004


## Завдання 15

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів
кожного стовпця матриці.

In [279]:
matrix15 = np.round(np.random.uniform(-0.5, 0.5, size=(3, 3)),3)

print('матриця\n', matrix15)
column_sums = np.sum(matrix15, axis=0)
column_sums_vector = column_sums.reshape(-1, 1)
print('вектор\n',column_sums_vector)

матриця
 [[-0.394  0.187  0.448]
 [ 0.374 -0.359 -0.224]
 [ 0.334 -0.207  0.378]]
вектор
 [[ 0.314]
 [-0.379]
 [ 0.602]]
